-- no-transaction
-- Drop the old, non-covering index now that 0017's covering index exists
-- (JEF-548). Its leading columns (name, bucket) are a superset of the old
-- index's (name, bucket DESC), so it serves every access pattern the old one
-- did — including the `ORDER BY bucket DESC LIMIT 1` latest-row lookup in
-- metric_facet's meta query, which just becomes a backward scan of the new
-- (ASC-declared) index — making the old index redundant. It's dropped rather
-- than kept alongside: the extra index would double the per-row index
-- maintenance cost on every ingest-time rollup upsert (each upsert touches
-- count/sum/avg/max, which both indexes would need to keep in sync) for no
-- read benefit.
--
-- CONCURRENTLY avoids taking a write lock against ingest's rollup upserts
-- while the drop completes; see 0017 for why this needs its own
-- `-- no-transaction` migration file rather than sharing one with the CREATE.
DROP INDEX CONCURRENTLY IF EXISTS metric_series_rollups_name_bucket_idx;
